### ISSUE TITLE
New time available to schedule a brownbag

### ISSUE THREAD

**Issue by nolleto** [Codeminer42/marvin-cm42#31]
I would like to run a command to know when is the next time available for a brownbag.

The command could be something like `!brownbagnexttimeavailable`, `!brownbagnextschedule`, `!brownbagavailability` or a better name.

And the answer would be the next Thursday after the last brownbag. So, if the last brownbag will be on January 13, 2021, the command result should be January 20, 2021.

**Comment by paulodiovani** [comment]
Getting the next available slot for a brownbag is pretty complex and would need to consider a few variables, making the code very complex. Just to list some:

- The schedule for brownbags on youtube is still manual, so there may be a few [already submitted](https://forms.gle/dPBDuQzi3gVTfuXbA) that are not scheduled on youtube yet.
- Because of the item above, there is no way to programmatically _reserve_ a slot right now.
- Would need to make date calculations and consider exceptions, like holidays.
- A better source of truth is the (aforementioned) form answers, but for that, we would need to read from Google Drive and not youtube, which requires a new api client and a lot more code.

## Proposal

As an alternative to the requested feature, which would be much more simple and yet be just as useful, I suggest that we just list the _**last**_ scheduled brownbag.

### Option 1: Get live broadcasts by descending order (if possible)

I don't see a way to list the live broadcasts in decrescent order in the API, which would make it much easier. However picks this issue, research if that is possible.
If so:

1. Use the current api client (https://github.com/Codeminer42/marvin-cm42/blob/6034508a1fe1abf964003255d93f99fc19ee3c5d/lib/google/youtube.js#L5-L16)
2. Update the client to accept a `sort` option and request by date in descending order
3. Limit to 1, which would be last

### Option 2: Get all and show the last one

In case there is really no way to change the sorting order.

1. Use the current api client (https://github.com/Codeminer42/marvin-cm42/blob/6034508a1fe1abf964003255d93f99fc19ee3c5d/lib/google/youtube.js#L5-L16) and get all the scheduled brownbags
2. Make as many requests are required to get all the schedule live broadcasts (must use `pageInfo.totalResults`, `pageInfo.resultsPerPage` and `nextPageToken` to check if there are more)
3. At the final request, get only the last schedule live broadcast and show to the user

## Youtube live broadcast API docs

https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/list?hl=en

**Comment by nolleto** [comment]
Nice! This is a good alternative so, maybe the command name could be something like `!brownbaglast`.
